version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./yolo11n-pose.pt:/app/yolo11n-pose.pt
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - yolo-pose-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - yolo-pose-network

networks:
  yolo-pose-network:
    driver: bridge 